### ISSUE TITLE
Conflict with CONNECT_ENABLE_VOICE_RESPONSE_INTERRUPT and Agent transfers when utilizing Elicit Response.

### ISSUE THREAD

**Issue by GGONCONCENTRIX** [aws-solutions/qnabot-on-aws#434] opened 2022-04-07 16:54 UTC
QNABot if transferring to agent after elicit response. With CONNECT_VOICE_INTTERRUPT_RESPONSE enabled.
Elicit response is fulfilled Returns 'OK'

Answer from QNABot query has Ok prepended. 'Fulfillment' response from QNABot is just the OK as it is our first sentence.

**Comment by ihmaws** [comment] 2023-06-26 16:20
Hi @GGONCONCENTRIX, unable to reproduce given the provided information.

Closing for now, but if you run into the issue again on the latest version, please create a new issue using the bug report template and we'll have another look.

**Closed by ihmaws** 2023-06-26 16:20 UTC
Labels: bug
