### ISSUE TITLE
Chatbot Import of Questions not working

### ISSUE THREAD

**Issue by VivekNidhi** [aws-solutions/qnabot-on-aws#537] opened 2023-01-06 16:13 UTC
**Describe the bug**
We are uploading series of questions into chatbot but they are not coming up. 

**To Reproduce**
Create a chatbot questions excel file and import them. The questions should appear in the chatbot

**Expected behavior**
The application should have the questions

**Please complete the following information about the solution:**
- [4.7.0 ] Version: 

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example, "_(SO0189) QnABot [...] **v0.0.1**_".

- [x] Region: [e.g. eu-west-1]
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [ ] Were there any errors in the CloudWatch Logs?

**Screenshots**
![image](https://user-images.githubusercontent.com/33089604/211051956-9e5a8310-1655-4272-84a8-3fa051d77c11.png)

**Comment by ihmaws** [comment] 2023-06-26 17:43
Hi @VivekNidhi, unfortunately unable to reproduce or investigate issues on this solution version. Closing issue for now.

See: https://github.com/aws-solutions/qnabot-on-aws/issues/572 for additional details. There have been several releases since v4.7.0 which may have resolved these issues.

@reimannlars, if you are seeing an issue on a newer version, please file a separate issue using the bug report template for the team to investigate and follow up on.

**Closed by ihmaws** 2023-06-26 17:43 UTC
Labels: bug
