### ISSUE TITLE
QnABot Excel/JSON Import Issue

### ISSUE THREAD

**Issue by GGONCONCENTRIX** [aws-solutions/qnabot-on-aws#483] opened 2022-07-05 18:16 UTC
When importing the json file and when a question exceeds 140 characters, the import feature within the QnABot console will still allow the import to continue without throwing an error. "Member must have length less or equal to 140"

**Comment by ihmaws** [comment] 2023-06-26 17:23
Hi @GGONCONCENTRIX, unable to reproduce given the provided information.

Closing for now, but if you run into the issue again on the latest version, please create a new issue using the bug report template and we'll have another look.

**Closed by ihmaws** 2023-06-26 17:23 UTC
Labels: bug
