### ISSUE TITLE
Client error calling response bots using voice

### ISSUE THREAD

**Issue by amendlik** [aws-solutions/qnabot-on-aws#682] opened 2024-01-25 15:23 UTC
**Describe the bug**
The QnABot web client fails using voice, if the match contains a response bot

**To Reproduce**
1. Define a `qna` document that includes a response bot. For example:
    - **Question:** "Ask my age"
    - **Answer:** "What is your age?"
    - **ResponseBot Hook:** "QNAAge"
    - **Response Session Attribute Namespace:** "age"
2. Open the client and click the microphone icon.
3. Say aloud, "Ask my age."

The web client will reply with "_Sorry, I had an error handling this conversation._"

The browser console displays this error:
```
converser error: TypeError: i.interpretations is undefined
    e https://lvd9c5ucg6.execute-api.us-west-2.amazonaws.com/prod/static/client.js:4240
    c https://lvd9c5ucg6.execute-api.us-west-2.amazonaws.com/prod/static/client.js:3914
    _invoke https://lvd9c5ucg6.execute-api.us-west-2.amazonaws.com/prod/static/client.js:3914
    g https://lvd9c5ucg6.execute-api.us-west-2.amazonaws.com/prod/static/client.js:3914
    i https://lvd9c5ucg6.execute-api.us-west-2.amazonaws.com/prod/static/client.js:56
    a https://lvd9c5ucg6.execute-api.us-west-2.amazonaws.com/prod/static/client.js:56
    promise callback*i https://lvd9c5ucg6.execute-api.us-west-2.amazonaws.com/prod/static/client.js:56
    a https://lvd9c5ucg6.execute-api.us-west-2.amazonaws.com/prod/static/client.js:56
    node_modules babel/runtime/helpers/esm/asyncToGenerator.js/n/</<@https://lvd9c5ucg6.execute-api.us-west-2.amazonaws.com/prod/static/client.js:56
    node_modules babel/runtime/helpers/esm/asyncToGenerator.js/n/<@https://lvd9c5ucg6.execute-api.us-west-2.amazonaws.com/prod/static/client.js:56
    promise callback*value https://lvd9c5ucg6.execute-api.us-west-2.amazonaws.com/prod/static/client.js:4240
    lexPostContent https://lvd9c5ucg6.execute-api.us-west-2.amazonaws.com/prod/static/client.js:4252
    promise callback*lexPostContent https://lvd9c5ucg6.execute-api.us-west-2.amazonaws.com/prod/static/client.js:4252
    y https://lvd9c5ucg6.execute-api.us-west-2.amazonaws.com/prod/static/client.js:16
    dispatch https://lvd9c5ucg6.execute-api.us-west-2.amazonaws.com/prod/static/client.js:22
    dispatch https://lvd9c5ucg6.execute-api.us-west-2.amazonaws.com/prod/static/client.js:16
    ondataavailable https://lvd9c5ucg6.execute-api.us-west-2.amazonaws.com/prod/static/client.js:4272
    value https://lvd9c5ucg6.execute-api.us-west-2.amazonaws.com/prod/static/client.js:4244
    e https://lvd9c5ucg6.execute-api.us-west-2.amazonaws.com/prod/static/client.js:4244
client.js:4272:4164
``` 

**Expected behavior**
1. Client should respond with, "What is your age?" and proceed to elicit an age value from the user.

**Please complete the following information about the solution:**
- [x] Version: **v5.4.5**
- [x] Region: **us-west-2**
- [x] Was the solution modified from the version published on this repository? **No**
- [x] If the answer to the previous question was yes, are the changes available on GitHub? **N/A**
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses? **Yes**
- [x] Were there any errors in the CloudWatch Logs? **No**

**Comment by jangidms** [comment] 2024-01-25 15:50
Hi @amendlik 
Thanks for reporting this.
We'll look into this and get back to you

**Comment by bobpskier** [comment] 2024-01-25 16:20
@amendlik Most likely this is due to an older version of LexWebUi embedded in QnABot. This issue was resolved in a more recent version of LexWebUi. The fix was in: https://github.com/aws-samples/aws-lex-web-ui/pull/579. You can work with the more recent version of LexWebUi by installing this directly from https://github.com/aws-samples/aws-lex-web-ui and using your deployed QnABot. The embedded version of LexWebUi was designed for limited testing of the bot vs production use. The standalone LexWebUi provides the full feature set of LexWebUi.

**Comment by jangidms** [comment] 2024-01-25 19:54
Thanks @bobpskier for your response. 
@amendlik On top of what Bob has mentioned, you can also try to upgrade to latest version of QnABot v5.5.0 where this functionality is working.

**Closed** 2024-01-25 19:55 UTC
Labels: bug
