### ISSUE TITLE
Received response status [FAILED] from custom resource during stack deployment

### ISSUE THREAD

**Issue by ejahnke** [aws-solutions/qnabot-on-aws#642] opened 2023-10-06 15:46 UTC
**Describe the bug**
During CFN stack deployment, the following error message is encountered: Received response status [FAILED] from custom resource. Message returned: getaddrinfo ENOTFOUND [search-opensearchdomai-ekp9vbjuwjni-rm4nechyxvlrfcyep7cgirym4u.ca-central-1.es.amazonaws.com](http://search-opensearchdomai-ekp9vbjuwjni-rm4nechyxvlrfcyep7cgirym4u.ca-central-1.es.amazonaws.com/) (RequestId: 1393dffa-8a77-4c2d-a4b6-2570ec56386b)

This causes a stack rollback.

After deleting the stack and retrying with "Preserve successfully provisioned resources" turned ON, the deployment succeeds.

**To Reproduce**
Steps to reproduce the behavior.
Unable to reproduce. Failure seems to occur the first time that deployment is attempted and subsequent attempts work.

**Expected behavior**
Expected behavior is for the CFN stack to complete successfully.

**Please complete the following information about the solution:**
- [5.4.2] Version: [e.g. v0.0.1]

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example, "_(SO0189) QnABot [...] **v0.0.1**_".

- [ca-central-1 ] Region: [e.g. us-east-1]
- [ no] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ yes] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?
- [ no] Were there any errors in the CloudWatch Logs?

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

**Comment by marcburnie** [comment] 2023-10-16 19:16
Closing as can't reproduce.

**Closed by marcburnie** 2023-10-16 19:16 UTC
Labels: bug
