### ISSUE TITLE
Questions are not being displayed in Designer after import was used.

### ISSUE THREAD

**Issue by iamcrisb** [aws-solutions/qnabot-on-aws#528] opened 2022-12-07 13:28 UTC
**Describe the bug**
Importing QnA's through content designer's import functionality causes the questions view to no longer display any questions. If the filter input field is being populated with an appropriate value then the questions are correctly displayed for that value.

**To Reproduce**

1. Use the import functionality to import your QnA's.
2. Navigate to edit view for questions.
3. No questions are being displayed

**Expected behaviour**
All the questions are being displayed whenever the filter input is empty
**Please complete the following information about the solution:**
- [x] Version: v5.2.4
- [x] Region: us-east-1
- [ ] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [ ] Were there any errors in the CloudWatch Logs?

**Screenshots**
<img width="506" alt="image" src="https://user-images.githubusercontent.com/41893422/206190538-01824243-2d90-42e8-877f-ea0e53b908fd.png">
<img width="506" alt="image" src="https://user-images.githubusercontent.com/41893422/206190580-4dd273c1-6e57-4e51-821d-a34e4e4781f7.png">
<img width="815" alt="image" src="https://user-images.githubusercontent.com/41893422/206190786-6f2341d3-0c5d-4d7d-99e5-c1a3c017be16.png">

**Additional context**
Tried adding a new Q through the UI to see if that changes anything. It doesn't

**Comment by marcburnie** [comment] 2023-09-26 12:46
Hello, apologies for the late follow-up. We have not been able to reproduce this issue. It sounds like the issue may be caused by a question that has special characters or is 'corrupting' the question list in some way, which is causing the remaining questions to not display, except when filtered. I have tried importing a variety of special cases but have not observed this issue.

Do you have the original file you imported that caused this issue?

I realize that due to the time that has passed that much of the information has been lost. Any additional information you could provide would help. If there is no new information then I will close this ticket.

**Comment by iamcrisb** [comment] 2023-10-02 12:59
Hi Marc, I no longer have the file and I'm no longer working on that project, but you are correct. As far as I remember the issue was indeed caused by one of the questions being "corrupted", but I don't remember the exact cause.

**Comment by marcburnie** [comment] 2023-10-04 13:11
Thanks for the feedback. I'll close this ticket for now, since I haven't been able to reproduce the issue and there haven't been other related tickets.

**Closed by marcburnie** 2023-10-04 13:11 UTC
Labels: bug
