### ISSUE TITLE
Can I use handlebars to get a property for the answer?

### ISSUE THREAD

**Issue by russell-oit** [aws-solutions/qnabot-on-aws#397] opened 2022-02-03 21:03 UTC
**Describe the bug**
I would like to have most questions repeat the question they think is being answered.

I figured I could append all answers to have:
It seems like you are asking: <question 1>
Is there a way to display the first question in the answer without hardcoding?

Thanks

**Expected behavior**
Use the first question to display the what question the bot is actually answering.

**Please complete the following information about the solution:**
Version 4.7.3

**Additional context**

**Comment by russell-oit** [comment] 2022-02-03 21:05
I would like to have most questions repeat the question they think is being answered.

I figured I could append all answers to have:
It seems like you are asking:  <question 1>
<The Answer>

Is there a way to display the first question in the answer without hardcoding?

Thanks

Version 4.7.3

**Comment by fhoueto-amz** [comment] 2023-08-15 18:01
This is an enahncement, not a bug.

**Comment by kroeter** [comment] 2023-09-14 19:36
Our team decided to not move forward with this recommendation. Will close the issue.

**Closed** 2023-09-14 19:37 UTC
Labels: enhancement
