### ISSUE TITLE
Error In QnA Bot Designer, Export Page "Request Failed: error response from endpoint" (Invalid backup Status)

### ISSUE THREAD

**Issue by AtulTrikha** [aws-solutions/qnabot-on-aws#486] opened 2022-07-07 06:06 UTC
**Describe the bug**
Getting Error in Export Page "Request Failed: error response from endpoint"

When I am selecting the **Export** option from the Menu in the QnA Bot Designer, I am getting an error "Request Failed: error response from endpoint" when the export page is opened.

Observation: All the entries for the backup file end with "*qna.json: **Completed**" but there is one entry in the Exports with "*qna.json: " (**without completed or any status**) and I believe that is causing the issue. I can export after clicking ok to the error and perform all the operations **except deleting this one entry "*qna.json: "**. Is there any way to resolve this even from the AWS console?

**To Reproduce**
Open QnA Bot Designer
Click Menu
Select Export

**Expected behavior**
I should be able to open the Export page without any error and should be able to delete the backups.

**Please complete the following information about the solution:**
- [ ] Version: [e.g. v5.1.2]

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example, "_(SO0189) QnABot [...] **v0.0.1**_".

- [ us-east-1] Region: [e.g. us-east-1]
- [No ] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [ No] Were there any errors in the CloudWatch Logs?

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

![image](https://user-images.githubusercontent.com/28661096/177703280-e331f09a-1533-44ca-8d5e-488d4dc5a6c6.png)

**Additional context**

**Comment by abhirpat** [comment] 2023-09-14 19:26
Thank you for raising this issue. We have acknowledged this and get back to you with our findings.

**Comment by jangidms** [comment] 2023-10-04 15:45
Hi @AtulTrikha 
Apologies for the delayed response.
We are not able to reproduce this issue in latest version of QnABot.
I would suggest to upgrade to latest version of QnABot. 

Please let me know if you still see this issue after upgrading.

**Comment by jangidms** [comment] 2023-10-05 20:17
Closing this issue as Export functionality is working fine in latest version.
Please open new issue if you experience any issue
Thanks

**Closed by jangidms** 2023-10-05 20:17 UTC
Labels: bug
