### ISSUE TITLE
custom terminology

### ISSUE THREAD

**Issue by jasonzhangvdr** [aws-solutions/qnabot-on-aws#455] opened 2022-05-13 16:33 UTC
**Describe the bug**
We used attached CSV file to import as custom terminology translation.
[EPCTerminology.csv](https://github.com/aws-solutions/aws-qnabot/files/8689404/EPCTerminology.csv)

Expecting word "ningún", while spanish translation result output as "ningzn"

**To Reproduce**
Import attached csv as custom teminology

**Expected behavior**
out put "ningzn" instead of "ningún"

**Please complete the following information about the solution:**
QnABot- [v5.1.1]

- [ ] Region: [us-east-1]
- [ ] Was the solution modified from the version published on this repository?  No
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?  NA
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?  NA
- [ ] Were there any errors in the CloudWatch Logs?  NA

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**
NA

**Comment by marcburnie** [comment] 2023-07-20 19:44
Thanks for reporting this issue and sorry for the delayed response. I haven't been able to reproduce the issue exactly, but I also found that the custom term is not substituted in place of the translation.  I'll let you know once we have a fix in the pipeline.

**Comment by marcburnie** [comment] 2023-09-26 13:23
The issue is the Amazon Translation engine. I have reproduced the problem in the Amazon Translate console using the English input: "You can import this product without incurring any fees or custom duties." which translated to "Puedes importar este producto sin incurrir en ningunos cargos o derechos de aduana." I have raised the issue with the Translate team and will update this ticket accordingly.

**Comment by marcburnie** [comment] 2023-09-28 19:15
Closing this ticket since it is pending action from the Amazon Translate team. I will re-open if there are further updates.

**Closed by marcburnie** 2023-09-28 19:15 UTC
Labels: bug
