### ISSUE TITLE
QnA Bot Content Designer Questionnaire export empty

### ISSUE THREAD

**Issue by VivekNidhi** [aws-solutions/qnabot-on-aws#538] opened 2023-01-06 16:23 UTC
**Describe the bug**
When content admin export contents from content designer its coming up black document.

**To Reproduce**
Login into content designer and export the questionnaire

**Expected behavior**
Able to export the questions for QnA Bot

**Please complete the following information about the solution:**
- [ [4.7.0] 

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example, "_(SO0189) QnABot [...] **v0.0.1**_".

- [ ] Region: [e.g. EU-west-1]

**Comment by ihmaws** [comment] 2023-06-26 17:44
Unfortunately, unable to reproduce or investigate issues on this solution version. Closing issue for now.

See: https://github.com/aws-solutions/qnabot-on-aws/issues/572 for additional details. Import/Export functionality seems to working as expected in the latest version.

**Closed by ihmaws** 2023-06-26 17:44 UTC
Labels: bug
