### ISSUE TITLE
Lambda creates about 1 bilion copies of file

### ISSUE THREAD

**Issue by Peterfalck** [aws-solutions/qnabot-on-aws#718] opened 2024-05-02 11:15 UTC
**Describe the bug**
Looking at previous release notes it seems that we are experiencing the same issue as was found in v.5.4.3 ([https://github.com/aws-solutions/qnabot-on-aws/releases/tag/v5.4.3] but we are running from a fresh 5.5.0 release installed new on February 8. The behavior we are experiencing is causing significant cost (+$10k per month) in a dev environment which obviously is not sustainable. Another weird thing is that the environment is complaining that we are running python 3.8 but according to the release logs we are upgraded to 3.10?!”

**Please complete the following information about the solution:**
- [ 5.5.0]

- [ ] Region: [[eu-central-1]]
- [ ] Was the solution modified from the version published on this repository? No
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?
- [ ] Were there any errors in the CloudWatch Logs? 

**Screenshots**
![image](https://github.com/aws-solutions/qnabot-on-aws/assets/62930638/07cfaf7a-95d3-407f-9c93-14c38e44d468)

**Additional context**

**Comment by fhoueto-amz** [comment] 2024-05-02 19:14
Thanks @Peterfalck. We are looking into this.

**Comment by abhirpat** [comment] 2024-05-02 20:06
Thank you for letting us know, Peter. 

A. Regarding Testall Lamba creating large number of versions of the file:
1. Based on our investigation, we found that this occurs when there are no Q&As in the designer and the Testall functionality is used. Please make sure Q&As are added to the designer before using Testall.
2. To stop Testall Lambda creating multiple versions, please set Concurrency to 0 by navigating to Testall Lambda > Concurrency > Edit > Set to 0. Please note that this will stop use of Testall functionality. If you want to reuse, it needs to be set to default once the issue is resolved.
3. We also recommend creating alerts using AWS Cost Management that would notify you of any anomalies: https://docs.aws.amazon.com/cost-management/latest/userguide/create-cost-budget.html

 B. Regarding the Python 3.8
 1. When I deployed latest version of QnaBot 5.5.1 and Check Lambda >  Functions > Runtime > I see all Python Lambdas using 3.10. Could you confirm what you're seeing on your end?
 2. Could you also check if you have install custom lambdas outside Qna that may be using older versions?

**Comment by Peterfalck** [comment] 2024-05-03 09:54
Sorry. The warnings was for Cognito
![image](https://github.com/aws-solutions/qnabot-on-aws/assets/62930638/b44c9a32-300a-474b-8402-32b96da3dccc)

**Comment by abhirpat** [comment] 2024-05-03 15:44
I can confirm that is not the function created by QnaBot on AWS. It appears to be from lex-web-ui. You can try asking about it here https://github.com/aws-samples/aws-lex-web-ui/issues

**Comment by abhirpat** [comment] 2024-05-08 16:51
Hi @Peterfalck, this issue with Testall is now resolved with the latest release v5.5.2. Thank you!

**Closed** 2024-05-08 16:52 UTC
Labels: bug
